version: "3.9"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
#      - DEBUG=1  # enable more verbose logs
      - ENFORCE_IAM=1 # enforce IAM policies
#      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} # for Pro license
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  ls:
    name: ls
